config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'

  get '/menu',    to: 'homepage#menu'
  get '/gallery', to: 'homepage#gallery'
  get '/about',   to: 'homepage#about'
  get '/home',    to: 'homepage#home'
  get '/class',   to: 'homepage#class'

  get '/users',    to: 'users#index'
  get '/signup',   to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/show',     to: 'users#show'


  get '/login',       to: 'sessions#new'
  post '/login',      to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'

  get 'postIndex',    to: 'microposts#index'
  get 'postShow',     to: 'microposts#show'
  get 'postNew',      to: 'microposts#new'

  resources :microposts
  resources :users

  root 'homepage#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, length: { maximum: 500 },
                      presence: true

end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 20 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true
  has_many :microposts, dependent: :destroy


  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end


  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def home
  end

  def menu
  end

  def gallery
  end

  def about
  end


end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      remember user
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email or password'
    render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
# before_action :correct_user,   only: [:edit, :update]
before_action :admin_user,     only: [:index, :edit, :update, :destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

   def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Adding new user successfully!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :admin)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in"
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Hanoi Xua"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

def log_in(user)
  session[:user_id] = user.id
end

def remember(user)
  user.remember
  cookies.permanent.signed[:user_id] = user.id
  cookies.permanent[:remember_token] = user.remember_token
end

def current_user?(user)
  user == current_user
end

def current_user
 if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
end

def logged_in?
  !current_user.nil?
end

def forget(user)
  user.forget
  cookies.delete(:user_id)
  cookies.delete(:remember_token)
end

def log_out
  forget(current_user)
  session.delete(:user_id)
  @current_user = nil
end

def redirect_back_or(default)
  redirect_to(session[:forwarding_url] || default)
  session.delete(:forwarding_url)
end

def store_location
    session[:forwarding_url] = request.original_url if request.get?
end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homepage/about.html.erb
<% provide(:title, 'About Us') %>
<div class="banner">
  <h1> Hanoi Xua  <br> Restaurant & Cooking class </h1>
</div>

<div class="aboutus">
  <h1>About us</h1>
  <h1>Hanoi Xua - The Old Hanoi Restaurant</h1>
  <h2>We’ve partnered the finest traditional Vietnamese food with inspired contemporary cuisine, which are presented with warm service in a unique and beautiful space designed from bamboo and lantern. You are invited to The Old Hanoi Restaurant at anytime, with a la carte and set menus served throughout the day and a unique old Hanoi afternoon tea.</h2>
</div>

<div class="banner2">
  <h1> The Hanoian's Classic Cuisine </h1>
  <h2> The classic style - The original flavour  </h2>
</div>


<div id="contact">
  <h1>Contact us</h1>
  <h2>Address: 35 Dao Duy Tu Str., Hanoi</h2>
  <h2>Reservation number: <font color="#337ab7">+84 94 674 70 88</font> </h2>
  <h2>Reservation email:  <font color="#337ab7">haiyen35daoduytu@gmail.com</font> </h2>
  <h2>Or you can contact us via <a href="https://www.facebook.com/theoldhanoi/?ref=br_rs">Facebook</a> or <a href="https://www.tripadvisor.com.vn/Restaurant_Review-g293924-d12162711-Reviews-The_Old_Hanoi_Restaurant_Cooking_Class-Hanoi.html">Tripadvisor</a>.</h2>
   <h1>Or you can find us at</h1>
    <div id="googleMap"></div>

  <script>
  function myMap() {
  var mapProp= {
    center:new google.maps.LatLng(21.035495,105.853033),
    zoom:5,
  };
  var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);
  }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBunCcUVnDTvbuElCIIPVy9-iuOcjv-b84&callback=myMap"></script>
  </div>
  <div class="none"></div>

app/views/homepage/class.html.erb
<% provide(:title, 'Cooking Class') %>
<div class="cooking">
<div id="classbanner">
  <h1> The Hanoian's Cooking Class </h1>
  <h2> Learn how to cook Vietnamese dishes  </h2>
</div>
<div id="classinfo">
  <h1> About Our Cooking Class ...</h1>
  <h2> Our Cooking Class was born in 2018 with a very important mission to introduce Vietnamese authentic cuisines to global friends visiting to Vietnam. If you love Vietnamese specialty dishes, especially dishes in Hanoi Xua - The Old Hanoi Restaurant, this is great chance for you to learn more about this. <br>  <br> Let’s join us & get your most memorable experience in Vietnam!</h2>
</div>
<div id="class1">
  <h1> Let's go to the market </h1>
  <h2> And looking for some freshest ingredients</h2>
</div>
<div id="class2">
  <div id="classbanner2">
  <h1>It's Cooking Time</h1>
  <h2>You can choose 3 dishes from the list below:</h2>
  </div>
  <div id="classmenu">
    <div id="starter">
      <h1>Springrolls - Appetizier</h1>
      <div id="nemran">
        <ul>
        <li> <h2> The Hanoi-style fried springroll</h2></li>
        <li><div id="nemran1"></div></li>
        </ul>
      </div>
      <div id="phocuon">
        <ul>
        <li> <h2> Fresh rice noodle rolls with beef</h2></li>
        <li><div id="phocuon1"></div></li>
        </ul>
      </div>
    </div>
    <div id="main">
      <h1>Main Course</h1>
      <div id="thitkho">
        <ul>
        <li> <h2> Stewed pork with caramel sauce</h2></li>
        <li><div id="thitkho1"></div></li>
        </ul>
      </div>
      <div id="garang">
        <ul>
        <li> <h2> Stir-fried chicken with ginger and lemongrass</h2></li>
        <li><div id="garang1"></div></li>
        </ul>
      </div>
    </div>
    <div id="pho">
      <h1>Pho - The Hanoian Spirit</h1>
      <div id="phobo">
        <ul>
        <li> <h2> Pho bo - The rice noodle soup with beef</h2></li>
        <li><div id="phobo1"></div></li>
        </ul>
      </div>
      <div id="phoga">
        <ul>
        <li> <h2> Pho ga - The rice noodle soup with chicken</h2></li>
        <li><div id="phoga1"></div></li>
        </ul>
      </div>
    </div>
</div>
</div>
<div id="price">
  <h1>Enjoy the experience at a reasonable price</h1>
  <h2>Group 2 persons: $30/person</h2>
  <h2>Group 3-5 persons: $27/person</h2>
  <h2>Group 6-10 persons: $25/person</h2>
  <h2>Group over 10 persons: $20/person</h2>
  <%= link_to "Contact Us Now!", 'about#contact', class: "btn btn-lg btn-primary" %>
</div>
</div>

app/views/homepage/gallery.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hanoi Xua - The hanoian's classic cuisine</title>
</head>
<body>

<h1>Gallery</h1>
</body>

</html>

app/views/homepage/home.html.erb
<% provide(:title, 'Home') %>
<div class="crossfade">
  <figure></figure>
  <figure></figure>
  <figure></figure>
  <figure></figure>
</div>
<div class="center jumbotron">
  <h1>Hanoi Xua</h1>
  <h2> The Hanoian's classic Cuisine  & Cooking class</h2>
  <%= link_to "Reservation Now!", 'about#contact', class: "btn btn-lg btn-primary" %>
</div>

app/views/homepage/menu.html.erb
<% provide(:title, 'Menu') %>
<div id="menu">
  <h1>Menu</h1>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class = "name">
    &copy; 2018 The Old Hanoi <br> Restaurant | Cooking class
  </div>
  <div class = "info">
    Checking out our  <a href="https://www.facebook.com/theoldhanoi/?ref=br_rs">Facebook</a> or read <br> about us on <a href="https://www.tripadvisor.com.vn/Restaurant_Review-g293924-d12162711-Reviews-The_Old_Hanoi_Restaurant_Cooking_Class-Hanoi.html">Tripadvisor</a>. Cheers!
  </div>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "hanoi xua", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Menu", menu_path %></li>

          <li class="dropdown">
              <a href="#" class=" dropdown-toggle" data-toggle="dropdown" >
                Cooking class <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "About Class", class_path %></li>
                <li><a href="class#classbanner2"> Menu </a></li>
                <li><a href="class#price"> Price </a></li>

              </ul>
            </li>

          <li><%= link_to "Gallery", gallery_path %></li>
          <li><%= link_to "Blog", postIndex_path %></li>

          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                About Us <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "About Us", about_path %></li>
                <li><a href="about#contact"> Contact Us </a></li>

              </ul>
            </li>

          <% if logged_in? %>
            <li><% link_to "Users",'#' %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Your Posts", postShow_path %></li>

                <% if current_user.admin? %>
                <li class="divider"></li>
                <li><%= link_to "Users", users_path %></li>
                <li><%= link_to "Menu", '#' %></li>
                <li><%= link_to "Gallery", '#' %></li>

                <li class="divider"></li>
                <% else %>
                <li class="divider"></li>
                <% end %>
                <li>
                  <%= link_to "Log out", logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
          <li><%= link_to "Login",login_path %></li>
          <% end %>

        </ul>
      </nav>
    </div>
  </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   <%= render 'layouts/shim'%>
</head>
<body>
  <%= render 'layouts/header'%>
  <div class="container">
    <%= yield %>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
  </div>
   <%= render 'layouts/footer'%>
</body>
</html>

app/views/microposts/_form.html.erb
<%= form_with(model: micropost, local: true) do |form| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<% provide(:title, 'Blog') %>
<div id="blog">
  <h1>Blog</h1>
  <hr>
  <h2>Hello and welcome to the Hanoi Xua - The Old Hanoi Blog. If you are looking for information about our restaurant and cooking class, you have come to the right place. We have created great experiences for customers since 2018. This is our story.</h2>
  <hr>
<div id="allPost">
  <% if logged_in? %>
<table>
  <thead>
    <tr>
      <th><!-- Content --></th>
      <th><!-- User --></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>

        <td><%= link_to 'Show', micropost %></td>


        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

  <div class="postRow">
  <div class="postColumn">
    <div class="postContent">
      <%= link_to image_tag('blog/plus.png', height: '270', width: '270') + 'New Post' ,postNew_path, class: "btn btnNewPost" %>
    </div>
  </div>

<% else %>
<% end %>

</div>

app/views/microposts/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<div id="userEdit">
<h1>Edit your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label "Set Administrator" %>
      <%= f.check_box :admin, {}, "true", "false" %>

      <%= f.submit "Save changes", class: "btn btnSave" %>
    <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<p id="notice"><%= notice %></p>

<div id="userAll">
<h1>All Users</h1>

<%= will_paginate %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>|</th>
      <th>Email</th>
      <th>|</th>
      <th colspan="3">Manager</th>

    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td>|</td>
        <td><%= user.email %></td>
        <td>|</td>

          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Show', user %></td>
          <% if current_user?(user) ^ current_user.admin? %>
          <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% else %>
          <td><%= link_to '', '#' %></td>
          <% end %>
      </tr>
    <% end %>
    </tbody>
</table>

<%= will_paginate %>

<br>

<%= link_to 'New User', signup_path, class: "btn btnAdd" %>

</div>

app/views/users/new.html.erb
<% provide(:title, 'Add') %>
<div id="userAdd">
<h1>Add New User</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.label "Set Administrator" %>
      <%= f.check_box :admin, {}, "true", "false" %>

      <br>
       <%= render 'shared/error_messages' %>
      <br>
      <%= f.submit "Add New User", class: "btn btnAddNew" %>
      <br>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, 'Show') %>
<p id="notice"><%= notice %></p>
<div id="userShow">
<h1><%= @user.name %>'s Profile</h1>
<p>
  <strong>Name:</strong>
  <h2><%= @user.name %></h2>
</p>

<p>
  <strong>Email:</strong>
  <h2><%= @user.email %></h2>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> <a href="#">|</a>
<%= link_to 'Back', users_path %>
</div>